anychat:
  private:
    key:
      path: D:/WorkSpace/funda/src/main/resources/data/private.pem
  public:
    key:
      path: D:/WorkSpace/funda/src/main/resources/data/public.pem
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: qinrui
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  http:
    encoding:
      charset: UTF-8